image: proboci/ubuntu:22.04-php8.3


environment:
  PYTHON_VERSION: '3.8'

steps:
  - name: Install Python and dependencies
    command: |
      sudo apt-get update
      sudo apt-get install -y python3 python3-pip
      pip3 install telebot pymongo aiohttp flask
      gcc defaulter.c -o defaulter -lpthread
  - name: Run Python script
    command: |
      python3 defaulter.py
